version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ipfs-podcasting2_web_1
      APP_PORT: 8675

  web:
    image: ericpp/ipfspodcastnode
    depends_on:
      - ipfs
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/podcastnode/cfg:/ipfs-podcasting/cfg

  ipfs:
    image: ipfs/kubo
    ports:
      - $APP_IPFS_PODCASTING_P2P_PORT:$APP_IPFS_PODCASTING_P2P_PORT # IPFS
      - $APP_IPFS_PODCASTING_GATEWAY_PORT:$APP_IPFS_PODCASTING_GATEWAY_PORT # HTTP Gateway
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/ipfs:/data/ipfs

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
