version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ipfs-podcasting2_web_1
      APP_PORT: 8675

  web:
    image: ericpp/ipfspodcastnode
    depends_on:
      - ipfs
    environment:
      IPFS_RPC_URL: "http://ipfs-podcasting2_ipfs_1:5001"
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/podcastnode/cfg:/ipfs-podcasting/cfg

  ipfs:
    image: ipfs/kubo
    ports:
      - $APP_IPFS_PODCASTING_P2P_PORT:$APP_IPFS_PODCASTING_P2P_PORT # IPFS
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/ipfs:/data/ipfs
